### ISSUE TITLE
Failed logins aren't propagated when using sockets

### ISSUE THREAD

**Issue by brendan-myers** [skygridio/skygrid-sdk-js#14]
When using socketio, if a user enters an invalid email/password combination, the error is not propagated correctly, and can't be handled.

```js
project.login(email, password).then(() => {
	console.log('success');
}).catch(error => {
	console.log('error', error.message);
});
```
```
message: "Authentication failed: Invalid email/password for 'brendan'"
stack:
"Error: Authentication failed: Invalid email/password for 'brendan'
    at r.<anonymous> (https://cdn.skygrid.io/sdk/js/skygrid-0.2.7.min.js:1:29296)
    at r.onack (https://cdn.skygrid.io/sdk/js/skygrid-0.2.7.min.js:11:11358)
    at r.onpacket (https://cdn.skygrid.io/sdk/js/skygrid-0.2.7.min.js:11:10718)
    at r.<anonymous> (https://cdn.skygrid.io/sdk/js/skygrid-0.2.7.min.js:3:13027)
    at r.emit (https://cdn.skygrid.io/sdk/js/skygrid-0.2.7.min.js:3:14073)
    at r.ondecoded (https://cdn.skygrid.io/sdk/js/skygrid-0.2.7.min.js:11:5909)
    at s.<anonymous> (https://cdn.skygrid.io/sdk/js/skygrid-0.2.7.min.js:3:13027)
    at s.r.emit (https://cdn.skygrid.io/sdk/js/skygrid-0.2.7.min.js:4:12713)
    at s.add (https://cdn.skygrid.io/sdk/js/skygrid-0.2.7.min.js:11:16534)
    at r.ondata (https://cdn.skygrid.io/sdk/js/skygrid-0.2.7.min.js:11:5862)"
```

**Comment by brendan-myers** [comment]
Same problem with errors from `signup()`.

**Comment by dakenblack** [comment]
I came across this while writing my guide, I believe I fixed it. the problem was that _socket.emit was swallowing up exceptions.

I tried it with this code
```
var Skygrid = require("skygrid");

done = () => process.exit(0);
handler = err => console.error(err);
hand = (err) => {
  console.log(typeof err)
}
// var project = new Skygrid.project("bWChK69S");
var project = new Skygrid.project("bWChK69S", { api:"rest"});
var schemaToUse;
project.loginMaster("1c6Ld7dGyPIe22p6cU37oBZl")
  .then(() => {
    return project.schema("A2dD9zxU").fetch();
  })
  .catch((err) => console.error('[[error]]' , err))
  .then(() => console.log(2),() => console.log(3))
  .then(done,done)
```
